### PR TITLE
add option to customize font size

### PR DESCRIPTION
**Pull request by hat3ph**
Add option to customize font size and also standardize the config name

### CODE REVIEW

**Comment by hat3ph** [comment]
add option to customize date format too

**Comment by 3ximus** [comment]
Thanks for the contribution.
I like that standardization of the config file names but I'm a bit afraid it will break the theme for people with their own configs. I would say we could either still allow for the old config names, and give an alert if they are in use ?

**Comment by hat3ph** [comment]
Maybe add a remark in the readme about the new config name changes?

**Comment by 3ximus** [comment]
> Maybe add a remark in the readme about the new config name changes?

Sure :+1:

**Pull request merged**
