### PR TITLE
Allow to customize font color

### PR DESCRIPTION
**Pull request by hat3ph**
Add option to customize font color

### CODE REVIEW

**Comment by 3ximus** [comment]
Hi there. Thanks for the contributions again.
Could you add the default color if the property is not set on the config file ?

**Comment by hat3ph** [comment]
You want something like this in the Main.qml?

color: config.actionBarFontColor || "#505050"

How about the font size?

But since you already have the master/default property file theme.conf, seem bit redundant to set another default property in the Main.qml.

**Comment by 3ximus** [comment]
Sure, you can leave it only on the master config then. I'll merge it.
Thanks

**Comment by hat3ph** [comment]
thanks

**Pull request merged**
